modLoader="javafml"
loaderVersion="[36,)"
license="McBotAI Non-Commercial Redistribution License (https://github.com/beasty-mods/McBotAI/blob/main/LICENSE)"

[[mods]]
modId="mcbotai"
version="v0.0.2"
displayName="McBotAI"
authors="Beasty-mod"
description='''Have some friends !'''

[[dependencies.mcbotai]]
modId="forge"
mandatory=true
versionRange="[36.2.42,)"
ordering="NONE"
side="BOTH"

[[dependencies.mcbotai]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"