'use strict';

const DROP_ATTRIBUTION_RADIUS = 2.5;
const DROP_ATTRIBUTION_WINDOW_MS = 4000;

/**
 * Detects when a master player hands the bot an item (drops it nearby and
 * the bot picks it up) and has the bot thank them — genuinely generated by
 * its own small chat model (ai/chatbrain.js), not a hardcoded string. Early
 * on, with an undertrained model, this may come out as a short fragment or
 * even nothing at all; that's the honest behavior of a from-scratch model,
 * not a bug. If nothing gets generated, it stays silent rather than
 * papering over that with a canned "Thanks!" — the point was for this to
 * be in its own (still-learning) language.
 */
function attachInteractions(bot, config) {
  const candidateDrops = new Map(); // entity id -> { ts, byMaster }

  function nearbyMaster(position) {
    if (!config.masters) return null;
    for (const name of config.masters) {
      const player = bot.players[name];
      if (player && player.entity && player.entity.position.distanceTo(position) <= DROP_ATTRIBUTION_RADIUS) {
        return name;
      }
    }
    return null;
  }

  bot.on('itemDrop', (entity) => {
    const master = nearbyMaster(entity.position);
    if (master) candidateDrops.set(entity.id, { ts: Date.now(), byMaster: master });
  });

  bot.on('playerCollect', (collector, collected) => {
    if (!collector || collector.id !== bot.entity.id) return;
    const record = candidateDrops.get(collected.id);
    if (!record) return;
    candidateDrops.delete(collected.id);
    if (Date.now() - record.ts > DROP_ATTRIBUTION_WINDOW_MS) return;

    const ai = bot.chatAI;
    if (!ai || !ai.canReplyNow()) return;
    const prompt = `${record.byMaster}: (hands Botie an item)\n${bot.username}:`;
    const reply = ai.reply(prompt);
    if (reply) {
      bot.chat(reply);
      ai.ingest(`${bot.username}: ${reply}\n`);
    }
  });

  // Periodic cleanup so stale never-collected candidates don't accumulate forever.
  const interval = setInterval(() => {
    const now = Date.now();
    for (const [id, rec] of candidateDrops) {
      if (now - rec.ts > DROP_ATTRIBUTION_WINDOW_MS * 3) candidateDrops.delete(id);
    }
  }, 15000);

  return { stop: () => clearInterval(interval) };
}

module.exports = { attachInteractions };
